name: "NSPanel Manager"
description: "Container for Sonoff NSPanel management with a simple and intuitive UI"
version: "0.1.22"
image: docker.io/nspanelmanager/nspanelmanager-{arch}
slug: "nspanelmanager"
url: "https://nspanelmanager.com"
webui: http://[HOST]:[PORT:8000]/
panel_icon: mdi:fit-to-screen
ports:
  8001/tcp: 8001

ingress: true
ingress_port: 8000
ingress_stream: true
environment:
  IS_HOME_ASSISTANT_ADDON: "true"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
